# データセット

## 南極大陸に生育するペンギンの大きさについての観測データ

```{r}
# library(palmerpenguins)
```


## とくしま動物園で飼育される動物の体の大きさと体重

```{r}
#| include: false
if (!file.exists("data-raw/tokushima_zoo_animals22.csv")) {
  library(magrittr)
  library(rvest)
  url <-
    "https://www.city.tokushima.tokushima.jp/zoo/gallery/ichiran.html"
  x <-
    read_html(url)
  # 2016-04-01
  x |>
    html_element(css = '#main > div.h1bg > div.update.clearfix > p') |>
    html_text()
  animals <-
    x |>
    html_elements(css = '#main > div.main_inner > div > p > span') |>
    html_text() %>%
    ensurer::ensure(length(.) == 22)
  
  tksmzoo_animals22 <-
    tibble::tibble(
      taxon = c("食肉類", "鳥類", "食肉類", "鳥類", "霊長類",
              "霊長類", "霊長類", "食肉類", "齧歯類", "食肉類",
              "鳥類", "偶蹄類", "食肉類", "食肉類", "鳥類",
              "食肉類", "霊長類", "鳥類", "鯨偶蹄類", "奇蹄類",
              "齧歯類", "鯨偶蹄類"),
      name = animals,
      body_length_cm = c(63.5, 100, 64, 110, 85,
                    66, 80, 168, 134, 250,
                    130, 175, 31, NA_real_, 1.2,
                    250, 35, 69, NA_real_, NA_real_,
                    40, NA_real_),
      weight_kg = c(6, 3.5, 5.4, 6.5, 60,
                10, 20, 80, 66, 225,
                # ホッキョクグマは平均体重のうち最大値を採用
                9, 220, 0.9, 30.3, 15,
                410, 1.1, 6, 140, NA_real_,
                1.5, NA_real_),
      link = c("https://ja.wikipedia.org/wiki/レッサーパンダ",
           "https://ja.wikipedia.org/wiki/ホオジロカンムリヅル",
           "https://ja.wikipedia.org/wiki/コツメカワウソ",
           "https://ja.wikipedia.org/wiki/カナダガン",
           "https://ja.wikipedia.org/wiki/チンパンジー",
           "https://ja.wikipedia.org/wiki/シシオザル",
           "https://ja.wikipedia.org/wiki/マントヒヒ",
           "https://ja.wikipedia.org/wiki/ピューマ",
           "https://ja.wikipedia.org/wiki/カピバラ",
           "https://ja.wikipedia.org/wiki/ライオン",
           "https://ja.wikipedia.org/wiki/アフリカハゲコウ",
           "https://ja.wikipedia.org/wiki/シロオリックス",
           "https://ja.wikipedia.org/wiki/ミーアキャット",
           "https://ja.wikipedia.org/wiki/シンリンオオカミ",
           "https://ja.wikipedia.org/wiki/コンドル",
           "https://ja.wikipedia.org/wiki/ホッキョクグマ",
           "https://ja.wikipedia.org/wiki/リスザル",
           "https://ja.wikipedia.org/wiki/フンボルトペンギン",
           "https://ja.wikipedia.org/wiki/リャマ",
           # ポニーは肩までの高さが147cm以下の馬の総称
           "https://ja.wikipedia.org/wiki/ポニー",
           "https://ja.wikipedia.org/wiki/モルモット",
           "https://ja.wikipedia.org/wiki/ヒツジ"))
  tksmzoo_animals22 |> 
    readr::write_csv("data-raw/tokushima_zoo_animals22.csv")
}
```

[とくしま動物園](https://www.city.tokushima.tokushima.jp/zoo/index.html)で飼育される
22種の動物（2016年4月1日時点の情報）について体の大きさ（体長 cm）と体重（kg）をデータセット化したものです。
体長と体重については各動物のWikipediaのページを参照して記録しています。
原則として、各種の体長および体重の最大値を記録しています。
適当な値の記載がなかった項目については欠損値を与えています。

データは[GitHubリポジトリ](https://github.com/uribo/tokupon_ds)に保存してあります。

https://github.com/uribo/tokupon_ds/blob/main/data-raw/tokushima_zoo_animals22.csv

