---
title: "はじめに"
---

## データ分析って何？

データ分析とは、
得られたデータを人間が利用できる形に変換することで
対象についての理解や予測を目指す手続き

データの取得は観測や実験により行われます。

データ分析を行うために統計学の知識を活用します。
統計学では確率論と呼ばれる数学の力を使うことでデータ分析の幅を広げることができます。

数学は理系の印象がありますが、データ分析は文理問わず求められる技能です。

データ分析には次の目的があります。

- データを<ruby>要約<rt>ようやく</rt></ruby>すること
- データの意味・関係を説明すること
- 新たに得られるデータに対する予測を行うこと

要約とは物事の中心となる大切な部分を短くまとめることです。
一般的にデータ分析の対象となるデータは<ruby>膨大<rt>ぼうだい</rt></ruby>です。
そのため一つ一つのデータを見ていくことは難しいです。
そこでデータを要約する方法として代表値によるデータの集約やグラフによるデータ可視化が行われます。
この方法について、コースの中でも[第2章](summary_statistics.qmd)と[第4章](visualization.qmd)で扱います。

２つ目の目的として、データがもつ意味やデータに含まれる値の関係性を説明することがあります。
例えば身長と体重を記録したデータから何が言えるでしょうか。


### データ分析のプロセス

課題や適切なデータを見つける、データを解析する、解析結果を利用する

### データを意思決定に役立てる

データ処理、分析のための専門知識を備える

データに含まれる誤差やバイアスといった性質を正しく理解した上で、
**データから有益な情報（価値）を引き出すための学問分野をデータサイエンス**と呼びます。

データサイエンスでは情報学と統計学の技能を生かして

また、データサイエンスにより企業や研究に貢献する人々のことをデータサイエンティストと言います。

## データ、グラフに騙されない

私たちの身の回りには数値やグラフがたくさんあります。

データを見て、何を強調して示したいか（作り手の意図。同じデータであっても何をどう示すかで見方が変わる

こうした**データ、グラフに騙されないための素養（リテラシー）が重要**になります。

<!-- https://en.wikipedia.org/wiki/Rabbit–duck_illusion -->

## データ分析で扱う問題

データ分析では「モデル」と呼ばれる考え方

統計モデルを使って問題の解決に挑みます。

[回帰](regression.qmd)と[分類](classification.qmd)

このコースでも、発展として簡単な回帰と分類問題に挑戦します。

::: callout-note
## R言語について

このコースではR言語を使った実習を行うよ。 R言語は統計計算と作図の機能に優れたプログラミング言語の一種だよ。 オープンソース・フリーソフトウェアと言って、誰もが自由に使うことができるんだ。

R言語に関心を持ったなら、付録の「[Rのイロハ](r_intro.qmd)」を見てみてね。

Rのインストール方法、簡単な使い方を紹介するよ。
:::

<!-- Pythonについても一言 -->

## まとめ

## 参考文献・URL

-   [@ezaki20]
